### ISSUE TITLE
zepto fails on npm run-script build

### ISSUE THREAD

**Issue by MikHulk** [madrobby/zepto#1241]
Hello,

I try to build zepto with a local installation of coffee-script. I followed the instructions from README:
```
npm install
npm run-script dist
```
from node_modules/zepto directory.
the installation didn't find coffee. I run npm-run-script from node_modules/zepto from here the path to coffee command is "coffee-script/bin/coffee". Must I put the pah to coffee in my PATH ? There are two files zepto.js and zepto.min.js in /dist but they are not are not the ones I built, if I remove them "npm run-script dist" doesn't rebuild it.
bellow the debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run-script', 'dist' ]
2 info using npm@2.15.9
3 info using node@v4.6.1
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info predist zepto@1.2.0
6 info dist zepto@1.2.0
7 verbose unsafe-perm in lifecycle true
8 info zepto@1.2.0 Failed to exec dist script
9 verbose stack Error: zepto@1.2.0 dist: `coffee make dist`
9 verbose stack spawn ENOENT
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:17:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid zepto@1.2.0
11 verbose cwd /home/mik/dev_nerim/admin4/git@tchernobyl.nerim.net:admin4/js_src/node_modules/zepto
12 error Linux 4.8.8-200.fc24.x86_64
13 error argv "/usr/bin/node" "/usr/bin/npm" "run-script" "dist"
14 error node v4.6.1
15 error npm  v2.15.9
16 error file sh
17 error code ELIFECYCLE
18 error errno ENOENT
19 error syscall spawn
20 error zepto@1.2.0 dist: `coffee make dist`
20 error spawn ENOENT
21 error Failed at the zepto@1.2.0 dist script 'coffee make dist'.
21 error This is most likely a problem with the zepto package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     coffee make dist
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs zepto
21 error Or if that isn't available, you can get their info via:
21 error
21 error     npm owner ls zepto
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
```

Thx

**Comment by basiclines** [comment]
+1 on this. You can't make custom Zepto builds inside the NPM package because the make file is missing from the package (among other build files). I don't know why there is different files inside the GitHub repo and the NPM package.

**Comment by mislav** [comment]
I think @basiclines is right. You mentioned you've tried to run aforementioned commands "from `node_modules/zepto` directory". This to me suggests that you've installed zepto as an npm package. However, our custom build instructions are written from the context of running it within zepto's git repository once you obtain it via git. Therefore:

```sh
git clone https://github.com/madrobby/zepto.git
cd zepto
npm install
npm run-script dist
```

This should work.
