### ISSUE TITLE
:has() selector is not supported

### ISSUE THREAD

**Issue by bitliner** [madrobby/zepto#1330]
If I click on an element with CSS selector `div:has(span)`, it throws 

```
Error: Evaluation failed: DOMException: Failed to execute 'querySelectorAll' on 'Document': 'div:has(span)' is not a valid selector. at selector (<anonymous>:1:23) at ExecutionContext.evaluateHandle (/usr/src/app/node_modules/puppeteer/lib/ExecutionContext.js:66:13) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by madrobby** [comment]
This is a jQuery CSS Extension that is not directly supported by Zepto. You can include the `selector` module to add (limited) support for it though.
